<a href="https://colab.research.google.com/github/majorrazor/Pytorch-/blob/main/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 00.PyTorch *Fundamentals*

Resource notebook: https://www.learnpytorch.io/

Git: https://github.com/mrdbourke/pytorch-deep-learning

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


# Introduction to Tensors
### Creating Tensors
torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [ ]:
scaler.ndim

0

In [ ]:
# Get tensor back as Python Int
scaler.item()

7

In [ ]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim


2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors
Torch random tensors

In [ ]:
# Create a random tensor of size (3, 4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8193, 0.5163, 0.3845, 0.4812],
        [0.5366, 0.3344, 0.2808, 0.3774],
        [0.6084, 0.8818, 0.5649, 0.3077]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape image
random_image_size_tensor = torch.rand(size=(224,224, 3)) #H, W Colour Channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
torch.rand(3,3)

tensor([[0.2859, 0.3404, 0.4676],
        [0.4796, 0.2162, 0.1954],
        [0.1712, 0.9472, 0.1749]])

### Zeros and Ones

In [ ]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
torch.arange(start=1, end=77, step=1)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76])

### Tensor datatypes


In [ ]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               device=None,
                               dtype=None,
                               requires_grad=False)
float_32_tensor


tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors



In [ ]:
s_tensor = torch.rand(3, 4)
s_tensor

tensor([[0.7035, 0.7457, 0.2750, 0.6435],
        [0.1583, 0.2545, 0.2865, 0.4935],
        [0.6041, 0.5885, 0.8518, 0.9501]])

In [ ]:
s_tensor.size, s_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [ ]:
print(s_tensor)
print(f'Datatype of tensor: {s_tensor.dtype}')
print(f'Datatype of tensor: {s_tensor.shape}')
print(f'Datatype of tensor: {s_tensor.device}')


tensor([[0.7035, 0.7457, 0.2750, 0.6435],
        [0.1583, 0.2545, 0.2865, 0.4935],
        [0.6041, 0.5885, 0.8518, 0.9501]])
Datatype of tensor: torch.float32
Datatype of tensor: torch.Size([3, 4])
Datatype of tensor: cpu


### Manipulating Tensors

In [ ]:
# Creating a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#...
tensor * 10
tensor

tensor([1, 2, 3])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
#^

### Matrix Multiplication

In [ ]:
print(tensor, '*', tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Mutiplaction
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
1*1 + 2*2 + 3*3 #manual matrix multiplication

14

In [ ]:
%%time
value = 0
for i in range (len(tensor)):
  value += tensor[i] * tensor[i]
  print(value)

tensor(1)
tensor(5)
tensor(14)
CPU times: user 666 µs, sys: 0 ns, total: 666 µs
Wall time: 671 µs


In [ ]:
torch.matmul(torch.rand(2,3), torch.rand(3, 2))

tensor([[1.0144, 0.6940],
        [0.5051, 0.8702]])

### ERROR

In [ ]:
# Shapes for matrix multiplication
tensor_a = torch.tensor([1, 2,
                         3, 4,
                         5, 6])
tensor_b = torch.tensor([7, 10,
                         8, 11,
                         9, 12])

In [ ]:
torch.matmul(tensor_a, tensor_b)

tensor(212)

### Finding min, max, mean, sum, etc

In [ ]:
x = torch.arange(0, 100, 10)

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
torch.mean(x.type(torch.float32)).mean()

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()


tensor(0)

In [ ]:
x[0]

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### RESHAPING, STACKING, SQUEEZING AND UNSQUEEZING

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#A view same memory as original...
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
torch.unsqueeze(x_reshaped,dim=1)


tensor([[[5., 2., 3., 4., 5., 6., 7., 8., 9.]]])

In [ ]:
x = torch. randn(2, 3, 5)
x.size()
torch.permute(x,(2,0,1)).size()

torch.Size([5, 2, 3])

In [ ]:
x_original = torch.rand(size=(224, 224, 3))

In [ ]:
x_permuted = x

In [ ]:
x_original.permute(2, 0, 1)

tensor([[[0.2461, 0.7766, 0.1787,  ..., 0.1873, 0.8537, 0.0693],
         [0.8805, 0.7269, 0.8769,  ..., 0.5474, 0.5767, 0.2971],
         [0.7000, 0.7865, 0.4355,  ..., 0.1279, 0.3742, 0.8867],
         ...,
         [0.5430, 0.4403, 0.7198,  ..., 0.8741, 0.7190, 0.2500],
         [0.2214, 0.9177, 0.5854,  ..., 0.4677, 0.6012, 0.0808],
         [0.9101, 0.6273, 0.1497,  ..., 0.6345, 0.9489, 0.5317]],

        [[0.5415, 0.8989, 0.5671,  ..., 0.3269, 0.1286, 0.5557],
         [0.1084, 0.5546, 0.1623,  ..., 0.0554, 0.3167, 0.5797],
         [0.8765, 0.8959, 0.7012,  ..., 0.2009, 0.4590, 0.1684],
         ...,
         [0.2933, 0.6292, 0.6061,  ..., 0.6034, 0.2401, 0.6609],
         [0.5588, 0.6124, 0.3609,  ..., 0.0278, 0.3474, 0.5068],
         [0.4780, 0.7612, 0.0448,  ..., 0.8325, 0.1703, 0.8739]],

        [[0.8941, 0.8719, 0.6300,  ..., 0.1549, 0.2440, 0.1640],
         [0.2556, 0.3376, 0.2236,  ..., 0.1255, 0.8187, 0.3441],
         [0.0863, 0.4240, 0.7221,  ..., 0.9843, 0.1694, 0.

## Indexing

In [ ]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][1][1]

tensor(5)

In [ ]:
x[:, 1, 1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

### PyTorch Tensors & NumPy

Numpy to Pytorch torch.from_numpy(ndarray)

Pytorch to Numpy torch.Tensor.numpy()



In [ ]:
import torch
import numpy as np


In [ ]:
array= np.arange(1.0, 8.0)
tensor= torch.from_numpy(array) # might be data type issue
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Count number of device
torch.cuda.device_count()


1